services:
  - type: web
    name: fitness-club-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: fitness-db
    plan: free
    databaseName: fitness_club
    user: fitness_user